using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class RandomAudioPlayer : MonoBehaviour
{
    // Audioquelle, die den Sound abspielt
    public AudioSource audioSource;
    public AudioClip [] clips;
    
    // Zuf채llig generierte Zeitintervalle (zwischen 1 und 15 Sekunden)
    public float randomTimeInterval;
    
    // Timer zur Verfolgung der verstrichenen Zeit
    private float timeSinceLastPlay= 0f;

    void Start()
    {
         audioSource = this.GetComponent<AudioSource>();
       
      
        // Generiere eine zuf채llige Zeitspanne zwischen 1 und 15 Sekunden
        randomTimeInterval = Random.Range(1f, 240f);
        
  
    }

    void Update()
    {
        // Z채hle die verstrichene Zeit
        timeSinceLastPlay += Time.deltaTime;

        // Wenn die verstrichene Zeit das zuf채llige Zeitintervall erreicht, spiele das Audio ab
        if (timeSinceLastPlay >= randomTimeInterval)
        {
            // Audio abspielen
            PlayAudio();

        }
    }

    // Funktion zum Abspielen des Audios
    void PlayAudio()
    {
        if (audioSource != null && !audioSource.isPlaying)
        {
            audioSource.clip = clips[(int)Random.Range(0,clips.Length)];
            audioSource.Play();
            Debug.Log("Audio wird abgespielt!");
        }
    }
}


